# Build the Android APK on push to the master branch
name: Build APK
on:
  push:
    branches:
      - main
      - testing

env:
  GODOT_VERSION: 4.1.3
  EXPORT_NAME: immersive-home

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Android Export
        run: |
          mkdir -v -p /build/android
          godot -v --export-debug --headless "Android" /build/android/immersive-home.apk
          ls -l .
          ls -l /build
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: immersive-home-debug
          path: /build/android/immersive-home.apk
